export type NetworkPro = {
  id: string;
  name: string;
  company: string;
  trade: string;
  city: string;
  state: string;
  phone: string;
  email: string;
  badge: "green" | "yellow" | "gray";
  license: string;
  insurance: "verified" | "unverified" | "lapsed";
  rating: number;
  jobs: number;
  yearsActive: number;
  builderApproved?: boolean;
  preferred?: boolean;
  attachedTo?: string[]; // property records
  note?: string;
};

export const NETWORK_TRADES = [
  "All",
  "Builder",
  "Roofer",
  "HVAC",
  "Plumber",
  "Electrician",
  "Home Inspector",
  "Insurance Agent",
  "Realtor",
  "Mortgage Lender",
  "Public Adjuster",
  "General Contractor",
] as const;

export const networkPros: NetworkPro[] = [
  {
    id: "creekside",
    name: "Creekside Homes",
    company: "creeksidenewhomes.com",
    trade: "Builder",
    city: "Cedar Springs",
    state: "TX",
    phone: "(555) 010-2200",
    email: "care@creeksidenewhomes.com",
    badge: "green",
    license: "TX-BLD-449821",
    insurance: "verified",
    rating: 4.9,
    jobs: 312,
    yearsActive: 18,
    builderApproved: true,
    preferred: true,
    attachedTo: ["Builder Handoff", "Structural Warranty", "Workmanship"],
    note: "Founding Orivaz partner — every Creekside home ships with a full Orivaz Digital Identity at handoff.",
  },
  {
    id: "summit-roof",
    name: "Summit Roofing Co.",
    company: "Summit Roofing",
    trade: "Roofer",
    city: "Cedar Springs",
    state: "TX",
    phone: "(555) 311-8821",
    email: "service@summitroof.io",
    badge: "green",
    license: "TX-ROOF-22841",
    insurance: "verified",
    rating: 4.8,
    jobs: 184,
    yearsActive: 12,
    preferred: true,
    attachedTo: ["Roof Install 2024", "Annual Roof Inspection"],
  },
  {
    id: "trane-tech",
    name: "Northstar Mechanical",
    company: "Trane Certified",
    trade: "HVAC",
    city: "Plano",
    state: "TX",
    phone: "(555) 488-1144",
    email: "service@northstarhvac.com",
    badge: "green",
    license: "TX-HVAC-99022",
    insurance: "verified",
    rating: 4.7,
    jobs: 421,
    yearsActive: 22,
    attachedTo: ["HVAC Startup", "Annual HVAC Service"],
  },
  {
    id: "rheem-plumb",
    name: "BlueLine Plumbing",
    company: "BlueLine Plumbing LLC",
    trade: "Plumber",
    city: "Frisco",
    state: "TX",
    phone: "(555) 224-7710",
    email: "ops@bluelineplumbing.com",
    badge: "green",
    license: "TX-PLB-44120",
    insurance: "verified",
    rating: 4.6,
    jobs: 198,
    yearsActive: 9,
    attachedTo: ["Water Heater Commission"],
  },
  {
    id: "clearview",
    name: "ClearView Inspections",
    company: "ClearView",
    trade: "Home Inspector",
    city: "McKinney",
    state: "TX",
    phone: "(555) 720-5510",
    email: "report@clearviewhi.com",
    badge: "green",
    license: "TX-INSP-7710",
    insurance: "verified",
    rating: 4.9,
    jobs: 612,
    yearsActive: 15,
    attachedTo: ["Pre-Purchase Inspection"],
  },
  {
    id: "janet-statefarm",
    name: "Janet Ortiz",
    company: "State Farm Agency",
    trade: "Insurance Agent",
    city: "Cedar Springs",
    state: "TX",
    phone: "(555) 488-1102",
    email: "janet.ortiz@sfagent.com",
    badge: "green",
    license: "TX-INS-118822",
    insurance: "verified",
    rating: 4.8,
    jobs: 0,
    yearsActive: 11,
    attachedTo: ["Homeowner Policy"],
  },
  {
    id: "mark-daniels",
    name: "Mark Daniels",
    company: "Daniels Realty",
    trade: "Realtor",
    city: "Cedar Springs",
    state: "TX",
    phone: "(555) 224-9019",
    email: "mark@danielsrealty.com",
    badge: "green",
    license: "TX-RE-552210",
    insurance: "verified",
    rating: 4.7,
    jobs: 88,
    yearsActive: 7,
    preferred: true,
  },
  {
    id: "freedom-mortgage",
    name: "Riley Park",
    company: "Lone Star Mortgage",
    trade: "Mortgage Lender",
    city: "Dallas",
    state: "TX",
    phone: "(555) 911-2233",
    email: "riley@lonestarlend.com",
    badge: "yellow",
    license: "NMLS 884122",
    insurance: "unverified",
    rating: 4.3,
    jobs: 142,
    yearsActive: 5,
  },
  {
    id: "voltforge",
    name: "VoltForge Electric",
    company: "VoltForge",
    trade: "Electrician",
    city: "Allen",
    state: "TX",
    phone: "(555) 660-4101",
    email: "dispatch@voltforge.io",
    badge: "green",
    license: "TX-ELEC-77120",
    insurance: "verified",
    rating: 4.8,
    jobs: 256,
    yearsActive: 14,
  },
  {
    id: "shield-pa",
    name: "Tara Lim",
    company: "Shield Public Adjusters",
    trade: "Public Adjuster",
    city: "Houston",
    state: "TX",
    phone: "(555) 220-9988",
    email: "tara@shieldpa.com",
    badge: "yellow",
    license: "TX-PA-29911",
    insurance: "verified",
    rating: 4.4,
    jobs: 76,
    yearsActive: 6,
  },
];
