project_id = "pldlvpibxobwehhsgxmn"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.recheck-professionals]
verify_jwt = false
